### PR TITLE
Enable unix builds

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Needs https://github.com/conda-forge/libignition-plugin-feedstock/pull/3

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin , please restart build

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@seanyen this is ready to be merged

/cc @wolfv @traversaro

**Comment by traversaro** [comment]
You may want to add dartsim at least on unix as a dependency, otherwise the only enabled physics engine would be TPE, that is just a simple kinematic engine.

**Comment by traversaro** [comment]
But we can also add dartsim in a following PR.

**Comment by Tobias-Fischer** [comment]
We might as well try :). Also (attempted to) fixed the other build warnings.

**Comment by traversaro** [comment]
The failure on Windows may be due to the advanced template machinery that may require VS2019. As a workaround, we may considering using clang-cl

**Comment by Tobias-Fischer** [comment]
Whoops, only saw your comment after my latest commit. Let's see whether it compiles without sdformat. I guess switching to clang-cl should be done in a new PR, otherwise it gets a little cluttered here ..

**Comment by Tobias-Fischer** [comment]
Alright, I'd say let's merge this and open an issue to add dartsim+sdformat to the win build?

**Comment by Tobias-Fischer** [comment]
See #7 and #8 for the issues to add dartsim/sdformat on Win

**Comment by traversaro** [comment]
> Alright, I'd say let's merge this and open an issue to add dartsim+sdformat to the win build?

Good idea!

**Review by traversaro — APPROVED** [review]

**Pull request merged**
