### PR TITLE
Bump version 3.2.0

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
I am not sure what's going on with the Win build and Clang. Do you have any idea @traversaro? Same fix should be applied to #14 which fails for the same reason.

**Comment by traversaro** [comment]
> I am not sure what's going on with the Win build and Clang. Do you have any idea @traversaro? Same fix should be applied to #14 which fails for the same reason.

It seems to be failing at an early stage when CMake is validating that clang-cl is fully functional. This could be a regression either in either Clang or CMake, or in the build environment. I guess we can check for ports that use clang-cl (such as https://github.com/conda-forge/pinocchio-feedstock/blob/master/recipe/bld.bat#L4) if they have something different now in their config.

**Comment by traversaro** [comment]
> > I am not sure what's going on with the Win build and Clang. Do you have any idea @traversaro? Same fix should be applied to #14 which fails for the same reason.
> 
> It seems to be failing at an early stage when CMake is validating that clang-cl is fully functional. This could be a regression either in either Clang or CMake, or in the build environment. I guess we can check for ports that use clang-cl (such as https://github.com/conda-forge/pinocchio-feedstock/blob/master/recipe/bld.bat#L4) if they have something different now in their config.

Other repos we could check for recent builds: https://github.com/search?l=Batchfile&q=org%3Aconda-forge+clang-cl.&type=Code .

**Comment by Tobias-Fischer** [comment]
So judging from the latest build on master we don't actually use clang - I think it might be a regression in the setup of vs2019?

**Comment by traversaro** [comment]
> So judging from the latest build on master we don't actually use clang - I think it might be a regression in the setup of vs2019?

Good point! Probably then it is a by-product of https://github.com/conda-forge/vc-feedstock/issues/36 : the activation script fails, and so CMake automatic detection of the compiler to use goes back to clang-cl .

**Comment by Tobias-Fischer** [comment]
Seems like something odd with dartsim linking is going on:

```
2021-06-24T02:04:12.0252209Z [77/136] cmd.exe /C "cd . && %BUILD_PREFIX%\Library\bin\cmake.exe -E vs_link_dll --intdir=dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\Llvm\x64\bin\lld-link.exe  dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\CustomFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\CustomMeshShape.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\EntityManagementFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\FreeGroupFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\JointFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\KinematicsFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\LinkFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\SDFFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\ShapeFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\SimulationFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\plugin.cc.obj  /out:bin\ignition-physics3-dartsim-plugin.dll /implib:lib\ignition-physics3-dartsim-plugin.lib /pdb:bin\ignition-physics3-dartsim-plugin.pdb /dll /version:3.2 /machine:x64 /INCREMENTAL:NO  %PREFIX%\Library\lib\dart-collision-ode.lib  %PREFIX%\Library\lib\ode_double.lib  %PREFIX%\Library\lib\dart-utils-urdf.lib  %PREFIX%\Library\lib\dart-utils.lib  %PREFIX%\Library\lib\urdfdom_sensor.lib  %PREFIX%\Library\lib\urdfdom_model_state.lib  %PREFIX%\Library\lib\urdfdom_model.lib  %PREFIX%\Library\lib\urdfdom_world.lib  %PREFIX%\Library\lib\console_bridge.lib  %PREFIX%\Library\lib\dart.lib  %PREFIX%\Library\lib\dart-external-odelcpsolver.lib  %PREFIX%\Library\lib\fcl.lib  %PREFIX%\Library\lib\ccd.lib  %PREFIX%\Library\lib\assimp-vc141-mt.lib  %PREFIX%\Library\lib\z.lib  %PREFIX%\Library\lib\IrrXML.lib  %PREFIX%\Library\lib\boost_system.lib  %PREFIX%\Library\lib\boost_filesystem.lib  %PREFIX%\Library\lib\octomap.lib  %PREFIX%\Library\lib\octomath.lib  %PREFIX%\Library\lib\sdformat10.lib  %PREFIX%\Library\lib\tinyxml2.lib  lib\ignition-physics3.lib  %PREFIX%\Library\lib\ignition-plugin1.lib  %PREFIX%\Library\lib\ignition-common3-graphics.lib  %PREFIX%\Library\lib\ignition-math6.lib  %PREFIX%\Library\lib\ignition-common3-profiler.lib  %PREFIX%\Library\lib\ignition-common3.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
2021-06-24T02:04:12.0262757Z FAILED: bin/ignition-physics3-dartsim-plugin.dll lib/ignition-physics3-dartsim-plugin.lib 
2021-06-24T02:04:12.0276967Z cmd.exe /C "cd . && %BUILD_PREFIX%\Library\bin\cmake.exe -E vs_link_dll --intdir=dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\Llvm\x64\bin\lld-link.exe  dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\CustomFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\CustomMeshShape.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\EntityManagementFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\FreeGroupFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\JointFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\KinematicsFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\LinkFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\SDFFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\ShapeFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\SimulationFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\plugin.cc.obj  /out:bin\ignition-physics3-dartsim-plugin.dll /implib:lib\ignition-physics3-dartsim-plugin.lib /pdb:bin\ignition-physics3-dartsim-plugin.pdb /dll /version:3.2 /machine:x64 /INCREMENTAL:NO  %PREFIX%\Library\lib\dart-collision-ode.lib  %PREFIX%\Library\lib\ode_double.lib  %PREFIX%\Library\lib\dart-utils-urdf.lib  %PREFIX%\Library\lib\dart-utils.lib  %PREFIX%\Library\lib\urdfdom_sensor.lib  %PREFIX%\Library\lib\urdfdom_model_state.lib  %PREFIX%\Library\lib\urdfdom_model.lib  %PREFIX%\Library\lib\urdfdom_world.lib  %PREFIX%\Library\lib\console_bridge.lib  %PREFIX%\Library\lib\dart.lib  %PREFIX%\Library\lib\dart-external-odelcpsolver.lib  %PREFIX%\Library\lib\fcl.lib  %PREFIX%\Library\lib\ccd.lib  %PREFIX%\Library\lib\assimp-vc141-mt.lib  %PREFIX%\Library\lib\z.lib  %PREFIX%\Library\lib\IrrXML.lib  %PREFIX%\Library\lib\boost_system.lib  %PREFIX%\Library\lib\boost_filesystem.lib  %PREFIX%\Library\lib\octomap.lib  %PREFIX%\Library\lib\octomath.lib  %PREFIX%\Library\lib\sdformat10.lib  %PREFIX%\Library\lib\tinyxml2.lib  lib\ignition-physics3.lib  %PREFIX%\Library\lib\ignition-plugin1.lib  %PREFIX%\Library\lib\ignition-common3-graphics.lib  %PREFIX%\Library\lib\ignition-math6.lib  %PREFIX%\Library\lib\ignition-common3-profiler.lib  %PREFIX%\Library\lib\ignition-common3.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
2021-06-24T02:04:12.0317268Z LINK: command "C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\Llvm\x64\bin\lld-link.exe dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\CustomFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\CustomMeshShape.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\EntityManagementFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\FreeGroupFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\JointFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\KinematicsFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\LinkFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\SDFFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\ShapeFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\SimulationFeatures.cc.obj dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\plugin.cc.obj /out:bin\ignition-physics3-dartsim-plugin.dll /implib:lib\ignition-physics3-dartsim-plugin.lib /pdb:bin\ignition-physics3-dartsim-plugin.pdb /dll /version:3.2 /machine:x64 /INCREMENTAL:NO %PREFIX%\Library\lib\dart-collision-ode.lib %PREFIX%\Library\lib\ode_double.lib %PREFIX%\Library\lib\dart-utils-urdf.lib %PREFIX%\Library\lib\dart-utils.lib %PREFIX%\Library\lib\urdfdom_sensor.lib %PREFIX%\Library\lib\urdfdom_model_state.lib %PREFIX%\Library\lib\urdfdom_model.lib %PREFIX%\Library\lib\urdfdom_world.lib %PREFIX%\Library\lib\console_bridge.lib %PREFIX%\Library\lib\dart.lib %PREFIX%\Library\lib\dart-external-odelcpsolver.lib %PREFIX%\Library\lib\fcl.lib %PREFIX%\Library\lib\ccd.lib %PREFIX%\Library\lib\assimp-vc141-mt.lib %PREFIX%\Library\lib\z.lib %PREFIX%\Library\lib\IrrXML.lib %PREFIX%\Library\lib\boost_system.lib %PREFIX%\Library\lib\boost_filesystem.lib %PREFIX%\Library\lib\octomap.lib %PREFIX%\Library\lib\octomath.lib %PREFIX%\Library\lib\sdformat10.lib %PREFIX%\Library\lib\tinyxml2.lib lib\ignition-physics3.lib %PREFIX%\Library\lib\ignition-plugin1.lib %PREFIX%\Library\lib\ignition-common3-graphics.lib %PREFIX%\Library\lib\ignition-math6.lib %PREFIX%\Library\lib\ignition-common3-profiler.lib %PREFIX%\Library\lib\ignition-common3.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:bin\ignition-physics3-dartsim-plugin.dll.manifest" failed (exit code 1) with the following output:
2021-06-24T02:04:12.0338241Z lld-link: error: undefined symbol: protected: __cdecl dart::dynamics::BodyNode::BodyNode(class dart::dynamics::BodyNode *, class dart::dynamics::Joint *, struct dart::common::detail::ComposeData<class dart::common::detail::CompositeData<class std::map<class std::type_index, class std::unique_ptr<class dart::common::Aspect::Properties, struct std::default_delete<class dart::common::Aspect::Properties>>, struct std::less<class std::type_index>, class std::allocator<struct std::pair<class std::type_index const, class std::unique_ptr<class dart::common::Aspect::Properties, struct std::default_delete<class dart::common::Aspect::Properties>>>>>, struct dart::common::detail::GetProperties>, struct dart::common::detail::GetProperties, class dart::dynamics::BodyNode> const &)
2021-06-24T02:04:12.0359928Z >>> referenced by %PREFIX%\Library\include\dart\dynamics\detail\Skeleton.hpp:83
2021-06-24T02:04:12.0366630Z >>>               dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\EntityManagementFeatures.cc.obj:(public: struct std::pair<class dart::dynamics::FreeJoint *, class dart::dynamics::BodyNode *> __cdecl dart::dynamics::Skeleton::createJointAndBodyNodePair<class dart::dynamics::FreeJoint, class dart::dynamics::BodyNode>(class dart::dynamics::BodyNode *, struct dart::dynamics::FreeJoint::Properties const &, struct dart::common::detail::ComposeData<class dart::common::detail::CompositeData<class std::map<class std::type_index, class std::unique_ptr<class dart::common::Aspect::Properties, struct std::default_delete<class dart::common::Aspect::Properties>>, struct std::less<class std::type_index>, class std::allocator<struct std::pair<class std::type_index const, class std::unique_ptr<class dart::common::Aspect::Properties, struct std::default_delete<class dart::common::Aspect::Properties>>>>>, struct dart::common::detail::GetProperties>, struct dart::common::detail::GetProperties, class dart::dynamics::BodyNode> const &))
2021-06-24T02:04:12.0372173Z >>> referenced by dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\SDFFeatures.cc.obj
2021-06-24T02:04:12.0373322Z 
2021-06-24T02:04:12.0378301Z lld-link: error: undefined symbol: protected: __cdecl dart::dynamics::ShapeNode::ShapeNode(class dart::dynamics::BodyNode *, struct dart::common::detail::ComposeData<class dart::common::detail::CompositeData<class std::map<class std::type_index, class std::unique_ptr<class dart::common::Aspect::Properties, struct std::default_delete<class dart::common::Aspect::Properties>>, struct std::less<class std::type_index>, class std::allocator<struct std::pair<class std::type_index const, class std::unique_ptr<class dart::common::Aspect::Properties, struct std::default_delete<class dart::common::Aspect::Properties>>>>>, struct dart::common::detail::GetProperties>, struct dart::common::detail::GetProperties, class dart::common::EmbeddedPropertiesAspect<class dart::dynamics::EntityNode<class dart::dynamics::TemplatedJacobianNode<class dart::dynamics::FixedJacobianNode>>, struct dart::dynamics::detail::EntityNodeProperties>, class dart::dynamics::FixedFrame, class dart::dynamics::ShapeFrame> const &)
2021-06-24T02:04:12.0383581Z >>> referenced by %PREFIX%\Library\include\dart\dynamics\detail\BodyNode.hpp:180
2021-06-24T02:04:12.0387015Z >>>               dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\SDFFeatures.cc.obj:(public: class dart::dynamics::ShapeNode * __cdecl dart::dynamics::BodyNode::createShapeNode<class dart::dynamics::Shape, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &>(class std::shared_ptr<class dart::dynamics::Shape> const &, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &))
2021-06-24T02:04:12.0400670Z >>> referenced by dartsim\CMakeFiles\ignition-physics3-dartsim-plugin.dir\src\ShapeFeatures.cc.obj
2021-06-24T02:04:12.0406972Z [78/136] %BUILD_PREFIX%\Library\bin\clang-cl.exe   -TP -DBOOST_ALL_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_TEST_DYN_LINK -DIGNITION_PHYSICS_RESOURCE_DIR=\"D:/bld/libignition-physics3_1624498916955/work/resources\" -DIGN_PROFILER_ENABLE=0 -DNOMINMAX -DTEST_WORLD_DIR=\"D:/bld/libignition-physics3_1624498916955/work/dartsim/worlds/\" -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DdIDEDOUBLE -Ddartsim_plugin_LIB=\"D:/bld/libignition-physics3_1624498916955/work/build/bin/ignition-physics3-dartsim-plugin.dll\" -I..\include -Iinclude -I..\ -I. -I..\test\gtest\include -Icore\include -I..\dartsim\include -Idartsim\include -I..\sdf\include -Isdf\include -I..\mesh\include -Imesh\include -imsvc %PREFIX%\Library\include\eigen3 -imsvc %PREFIX%\Library\include\ignition\math6 -imsvc %PREFIX%\Library\include\ignition\plugin1 -imsvc %PREFIX%\Library\include\ignition\cmake2 -imsvc %PREFIX%\Library\include -imsvc %PREFIX%\Library\CMake\..\include -imsvc %PREFIX%\Library\include\ignition\common3 -imsvc %PREFIX%\Library\include\sdformat-10.3\sdf\.. /permissive- /D_USE_MATH_DEFINES /MD /O2 /Ob2 /DNDEBUG /Gy /W2 /Zi /GL  -Wall -Wextra -Wno-long-long -Wno-unused-value -Wfloat-equal -Wshadow -Winit-self -Wswitch-default -Wmissing-include-dirs  /EHsc -msse -msse2 -mfpmath=sse /permissive- -std:c++17 /showIncludes /Fodartsim\CMakeFiles\UNIT_JointFeatures_TEST.dir\src\JointFeatures_TEST.cc.obj /Fddartsim\CMakeFiles\UNIT_JointFeatures_TEST.dir\ -c -- ..\dartsim\src\JointFeatures_TEST.cc
```

**Comment by Tobias-Fischer** [comment]
This is ready to go @traversaro - changing back to MSVC compilation did the trick.

**Review by traversaro — APPROVED** [review]

**Pull request merged**
