### PR TITLE
Add new mantainers

### PR DESCRIPTION
**Pull request by traversaro**
@Tobias-Fischer do you want to be added as well to reduce the bus factor?

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Yes please, thanks :)

**Comment by traversaro** [comment]
> 
> 
> Yes please, thanks :)

Done!

**Comment by traversaro** [comment]
The usual waiting time of 7 days passed, could it make sense to merge this? @conda-forge/core @wolfv

**Comment by wolfv** [comment]
Thanks for taking this over!

**Pull request merged**
