### PR TITLE
Add PR 437 to fix https://github.com/RoboStack/ros-humble/issues/33

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

See https://github.com/RoboStack/ros-humble/issues/33:
```
RuntimeError: copy_symlink: The file or directory is not a reparse point.: 
"C:\Users\runneradmin\conda_pkgs_dir\libignition-physics5-5.2.0-hef61a30_2\Library\lib\ign-physics-5\engine-plugins\ignition-physics-bullet-plugin.dll", 
"C:\bld\ros-humble-ros-gz-sim-0_1671085464153\_h_env\Library\lib\ign-physics-5\engine-plugins\ignition-physics-bullet-plugin.dll"
```

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
The unversioned version is still being installed via a copy. I think having both copy + symlink led to issues. According to the logs, both dlls (unversioned and versioned) are found properly now by conda-build, whereas the previous build had a 0-byte unversioned dll that caused issues.

**Comment by traversaro** [comment]
> The unversioned version is still being installed via a copy. I think having both copy + symlink led to issues. According to the logs, both dlls (unversioned and versioned) are found properly now by conda-build, whereas the previous build had a 0-byte unversioned dll that caused issues.

Ok, great!

**Pull request merged**
